### ISSUE TITLE
No 0.4.2 tag on GitHub

### ISSUE THREAD

**Issue by QuLogic** [t-makaro/animatplot#55]
It appears that there's a 0.4.2 on PyPI, but the corresponding tag for it has not been pushed to GitHub.

**Comment by dschwoerer** [comment]
I think it is not even present at all - the 0.4.2 seems to be a backport of #53 - but the changes are not in the 0.4.x branch.

I was working on using directly the appropriate commit to get the latest changes to fedora, but I don't think it is currently possible without redoing the backport to get a similar result the what is on pypi.

**Comment by t-makaro** [comment]
Back when I did 0.4.2, I just took the then master branch and locally changed the version to release 0.4.2 since #53 was the only change. Yes, that was bad practice, but I'm certainly not going to fix it now. I'm currently working on fixing tests and ensuring compatibility with the latest python/matplotlib versions and getting CI to work again. I will cut a 0.4.3 or 0.5.0 release properly. Then I will look into existing pull requests and issues again.
